version: '3'
services:
    php:
        container_name: snappfood_php
        build:
            context: ./Docker/config/php
        volumes:
            - ./:/usr/share/nginx
        networks:
            snappfood-network:

    nginx:
        container_name: snappfood_nginx
        image: nginx:latest
        ports:
            - 8001:80
        volumes:
            - ./:/usr/share/nginx
            - ./Docker/config/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            snappfood-network:

    mysql:
        container_name: snappfood_mysql
        image: mysql:5.7.22
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - ./Docker/data/mysql:/var/lib/mysql
        networks:
            snappfood-network:

networks:
    snappfood-network:


